const projectData = [
  {
    title: "Dev-Overflow",
    image: "./devflow.png",
    description: "Learing next.js",
    link: "https://web-dev-next-js.vercel.app/",
    git: "https://github.com/CodeMaverick07/WebDev_next.js",
  },
  {
    title: "Hack-ai-thon",
    image: "./hackthon.png",
    description: "Hackthon Information website for council",
    link: "hhttps://hack-ai-thon-sable.vercel.app/",
    git: "https://github.com/CodeMaverick07/Hack-ai-thon",
  },
  {
    title: "Inter-Oasis",
    image: "./invictus.png",
    description: "React.js",
    link: "https://invictus-hackthon-hemant.vercel.app/",
    git: "https://github.com/CodeMaverick07/Invictus_Hackthon",
  },
  {
    title: "Coucil-website",
    image: "./aico.png",
    description: "Learing Front end with tailwind",
    link: "https://ai-colegion2.vercel.app/",
    git: "https://github.com/CodeMaverick07/aiColegion",
  },
  {
    title: "Travling_Histroy_Saver",
    image: "./wallpaper1.jpg",
    description: "save your all Travling_Histroy ",
    link: "https://travling-histroy-saver-hemantjatal.vercel.app/",
    git: "https://github.com/CodeMaverick07/travling_histroy_saver",
  },
  {
    title: "Food-Ordering-App",
    image: "./meals.png",
    description: "Used Lot of Hooks in it",
    link: "https://food-ordering-app-tras.vercel.app/",
    git: "https://github.com/CodeMaverick07/Food-ordering-app.git",
  },
  {
    title: "Eat-N-Split",
    image: "./split.png",
    description: "Learned State Management",
    link: "https://eat-n-split-8pjv9ty7o-tomatotwister.vercel.app/",
    git: "https://github.com/CodeMaverick07/eat-n-split.git",
  },
  {
    title: "Keeper-App",
    image: "./keeper.png",
    description: "Learned State Management",
    link: "https://keeper-app-ob2u.vercel.app/",
    git: "https://github.com/CodeMaverick07/keeper-app.git",
  },
  {
    title: "Drum-Kit",
    image: "./drumkit.png",
    description: "DOM",
    link: "https://tomatotwister.github.io/drum-kit/",
    git: "https://github.com/CodeMaverick07/drum-kit.git",
  },
  {
    title: "Expanding-Cards",
    image: "./expand.png",
    description: "Just for fun",
    link: "https://tomatotwister.github.io/expanding-anime-cards/",
    git: "https://github.com/CodeMaverick07/expanding-anime-cards.git",
  },
  {
    title: "Memory-Game",
    image: "./memory.png",
    description: "Basic Java-script",
    link: "https://tomatotwister.github.io/js-memory-game/",
    git: "https://github.com/CodeMaverick07/js-memory-game.git",
  },
  {
    title: "Double-Vertical-Slider",
    image: "./up slider.png",
    description: "For highlight",
    link: "https://tomatotwister.github.io/double-vertical-slider/",
    git: "https://github.com/CodeMaverick07/double-vertical-slider.git",
  },
  {
    title: "Rotating-Navigation",
    image: "./rotate.png",
    description: "It look nice",
    link: "https://tomatotwister.github.io/Rotating-navigation/",
    git: "https://github.com/CodeMaverick07/Rotating-navigation.git",
  },
];

export default projectData;
